### ISSUE TITLE
Released binary doesn't seem to run

### ISSUE THREAD

**Issue by rilysh** [lucasmz1/Qemu_Appimage#1]
Hello, I'm using https://github.com/lucasmz1/Qemu_Appimage/releases appimage of QEMU, however whatever I tried to run it, I couldn't be able to run the QEMU appimage. Tracing down and it seems like the appimage file is exiting for some reason without an error. `echo $?` shows it returns `0`.

I'm not sure what architecture against this build was done. I'm using this appimage on Debian 11 (x86_64).

**Comment by lucasmz1** [comment]
Hello sorry for the late reply I was busy doing a lot of things.

this command generate a HD file ./QEMU-x86_64.AppImage qemu-img create -f qcow2 windows10.qcow2 30G

this other command boot the .iso file into qemu  ./QEMU-x86_64.AppImage qemu-system-x86_64 -enable-kvm -cpu host -smp cores=2 -m 4096m -name 'Manjaro' -boot d -hda ~/Documentos/Manjaro.qcow2 -cdrom ~/Documentos/manjaro-gnome-21.3.7-220816-linux515.iso

you can run any arch you want it. you just need to pass the argument to the appimage.

any doubts come to me, on my telegram: @lucasmzainote21.
I also have a group called appimage users in telegram where I teach how to bundle appimages unfortunately it's all in portuguese.

**Comment by lucasmz1** [comment]
> Hello, I'm using https://github.com/lucasmz1/Qemu_Appimage/releases appimage of QEMU, however whatever I tried to run it, I couldn't be able to run the QEMU appimage. Tracing down and it seems like the appimage file is exiting for some reason without an error. `echo $?` shows it returns `0`.
> 
> I'm not sure what architecture against this build was done. I'm using this appimage on Debian 11 (x86_64).

I hope I've answered you question in above.

**Comment by lucasmz1** [comment]
byt the way don't forget to change the name of ./QEMU-AppImage to ./QEMU-4.2.0.Appimage give the full path to the .iso file and also to HDD file.
down bellow you may find useful commands.
https://github.com/lucasmz1/Qemu_Appimage/blob/main/qemu%20comando

**Comment by rilysh** [comment]
> Hello sorry for the late reply I was busy doing a lot of things.
> 
> this command generate a HD file ./QEMU-x86_64.AppImage qemu-img create -f qcow2 windows10.qcow2 30G
> 
> this other command boot the .iso file into qemu ./QEMU-x86_64.AppImage qemu-system-x86_64 -enable-kvm -cpu host -smp cores=2 -m 4096m -name 'Manjaro' -boot d -hda ~/Documentos/Manjaro.qcow2 -cdrom ~/Documentos/manjaro-gnome-21.3.7-220816-linux515.iso
> 
> you can run any arch you want it. you just need to pass the argument to the appimage.
> 
> any doubts come to me, on my telegram: @lucasmzainote21. I also have a group called appimage users in telegram where I teach how to bundle appimages unfortunately it's all in portuguese.

Thank you, I was able to run it.
Since my problem is solved, I'll close the issue now.
Thanks again!
