### ISSUE TITLE
[Just Note] don't using apt or apt-get install , using aptitude 

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#11]
the apt and apt-get just not inclohe all dependency

**Comment by lucasmz1** [comment]
what are you doing ? I need you to be more specific, without that it's kinda complicated for me to help you!

**Comment by zen0bit** [comment]
I think he treid build from master with broken build. (dependecy issue you already solved..)
check time

**Comment by lucasmz1** [comment]
@zen0bit Thank you brother!
