### ISSUE TITLE
feature request: remmina , ibus-input(important) appimage

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#12]
hi, i sorry, 
i have not time to test and rebuild appimage.
because , i need to make master graduate some work. and find work and ready for the interview.

and next . maybe is july , 2024

and. i have some request , it just the ibus-input
i always using ibus to input eng. 

and i see someone is build ibus-rime success: https://github.com/hchunhui/ibus-rime.AppImage

see you next time. thank you :")

**Comment by lucasmz1** [comment]
well if you need I can teach you how to make an appimage from all this apps, I can teach you!
it's easier.
I do prefer that cause I also have a lot of work to do I just cannot stay playing around with all this appimages that I make... it's too many stuff that I run in here.
hope you understand that.
