### ISSUE TITLE
i have question, how to fixed pycharm community with use libunionpreload.so to build appimage

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#13]
when i use 
```
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}/libunionpreload.so"
```

this to AppRun, i success builded pycharm appimage
but pycharm appimage open project folder is derect folder is appimage internal folder path, i don't how to fixed

**Comment by lucasmz1** [comment]
well I guess maybe you're missing some env variable like export XDG_CONFIG_HOME="${HOME}/config" export XDG_DATA_HOME="${HOME}/data"

**Comment by lucasmz1** [comment]
some appimages needs this envs to run perfectly

**Comment by newyorkthink** [comment]
> some appimages needs this envs to run perfectly

this is AppRun
```
 #!/usr/bin/env bash

HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}/libunionpreload.so"

export PATH="${HOME}/":"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$PATH"
export PERLLIB="${HOME}/":"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$PERLLIB"
export LD_LIBRARY_PATH="${HOME}/":"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$LD_LIBRARY_PATH"
export XDG_DATA_DIRS="${HOME}/":"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$XDG_DATA_DIRS"

EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
exec ${EXEC} "$@"
```

and i try use this , they quick disappeared home path

![Peek 2024-04-27 10-27](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/b17bf48b-287b-4567-a6dd-56ef1d24d66e)

**Comment by newyorkthink** [comment]
> data

and i add XDG_CONFIG_HOME

```
#!/usr/bin/env bash

HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}/libunionpreload.so"

export PATH="${HOME}/":"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$PATH"
export PERLLIB="${HOME}/":"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$PERLLIB"
export LD_LIBRARY_PATH="${HOME}/":"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$LD_LIBRARY_PATH"
export XDG_DATA_DIRS="${HOME}/":"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$XDG_DATA_DIRS"
export XDG_CONFIG_HOME="${HOME}"/data:"${HOME}"/:"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$XDG_CONFIG_HOME"

EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
exec ${EXEC} "$@"

```

and it not working index
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/2c9cadf5-16d7-4d7a-a735-c66b89ec271a)

**Comment by newyorkthink** [comment]
i try every ,. it just not fixed:
```
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}/libunionpreload.so"

export PATH="${HOME}"/data:"$HOME"/:/home/user:"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$PATH"
export PERLLIB="${HOME}"/data:"$HOME"/:/home/user:"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$PERLLIB"
export LD_LIBRARY_PATH="${HOME}"/data:"$HOME"/:/home/user:"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$LD_LIBRARY_PATH"
export XDG_DATA_DIRS="${HOME}"/data:"$HOME"/:/home/user:"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$XDG_DATA_DIRS"
export XDG_CONFIG_DIRS="${HOME}"/data:"$HOME":/home/user:"$HERE"/usr/bin:"$HERE"/usr/lib:"$HERE"/usr/share:"$XDG_CONFIG_DIRS"
export XDG_CONFIG_HOME="/home/user"


EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
exec ${EXEC} "$@"
```

**Comment by lucasmz1** [comment]
Well I'll try to bundle this application later, to see what's going on in your appimage. But please have in mind not all the apps are possible to be bundled and work perfectly. I need to have a look myself in this specific case.

**Comment by newyorkthink** [comment]
> Well I'll try to bundle this application later, to see what's going on in your appimage. But please have in mind not all the apps are possible to be bundled and work perfectly. I need to have a look myself in this specific case.

thank you, i will wait for you build with pycharm CE

**Comment by lucasmz1** [comment]
@newyorkthink I found a simple solution, here it is: use the AppRun from appimagekit https://github.com/AppImage/AppImageKit/releases it's writing in C. I've packed pycharm as appimage and it worked.

I belive it's because the env variables are opened lie this -> export PATH="${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}" 

if you need better support look for me in telegram @zainotel there I can record videos and send to you explaning the steps I take to pack the most part of my apps.

**Comment by newyorkthink** [comment]
> @newyorkthink I found a simple solution, here it is: use the AppRun from appimagekit https://github.com/AppImage/AppImageKit/releases it's writing in C. I've packed pycharm as appimage and it worked.
> 
> I belive it's because the env variables are opened lie this -> export PATH="${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}"
> 
> if you need better support look for me in telegram @zainotel there I can record videos and send to you explaning the steps I take to pack the most part of my apps.

i send some info for you on the telegram recently

**Comment by newyorkthink** [comment]
discuss to the telegram
