### ISSUE TITLE
hi you builded the new version cannot run in my os,

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#14]
i just current run you old build version
you old version have 1.3GB
but you new builded version just 1.1GB
is decline 200MB size, 
i think your new version abandon to some lib file

**Comment by lucasmz1** [comment]
@newyorkthink I know that. I saw that today earlier, what happend: when I tried to build the github gave me a warning that meson was needing glib >= 2.66 but the ubuntu 20.04 hasn't, so what I did I compiled the the glib and also the new qemu version is with it. but the libglib inside of qemu is mismatching with the version on your host os, so then what I am doing is removing it from the appimage, but don't worry libglib-20.so.0 is in all over distros. wait for the new build that will be accomplished in few minutes I am pretty much sure everything will work fine back again.

**Comment by lucasmz1** [comment]
sorry for the inconvenience

**Comment by lucasmz1** [comment]
but if you are on the hurry you can go and unpack the appimage with the ./QEMU-x86_64.appimage --appimage-extract and delete by yourself the libglib-2.0.so.0 from the lib directory and everything will start to work again.

**Comment by newyorkthink** [comment]
it work
