### ISSUE TITLE
how to add usb driver in kvm machine with use this qemu appimage?

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#15]

**Comment by lucasmz1** [comment]
@newyorkthink 
try this

https://chatgpt.com/share/447b4de0-16df-4dd8-89d7-ea6d599012d7

**Comment by newyorkthink** [comment]
> @newyorkthink try this
> 
> https://chatgpt.com/share/447b4de0-16df-4dd8-89d7-ea6d599012d7

hi, it not working with use your kvm appimage

first:
lsusb
Bus 004 Device 013: ID 058f:6387 Alcor Micro Corp. Flash Drive

i add this command to kvm -device usb-host,hostbus=4,hostaddr=13
it show 
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/386b10dd-8190-4959-9678-9e62fad6cb90)

,so, i run second function

            -device usb-host,vendorid=0x058f,productid=0x6387 , but it not show usb driver in the kvm machine
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/c1f462cd-aec9-4f71-ab9d-caba234c351f)

**Comment by lucasmz1** [comment]
well my friend I'm not a qemu specialist, it's complicated to me. you should try to email the qemu devs or even have a good read in the qemu wiki.
sorry for don't help you, my first idea when builded this application was only for run a basic vm in way to avoid distro hopping.

have a read in this article in the qemu wiki https://qemu-project.gitlab.io/qemu/system/devices/usb.html

**Comment by newyorkthink** [comment]
thank you
