### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#2]
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/e08e3bd0-c936-42a7-b97a-0f2b8e93e32c)

**Comment by zen0bit** [comment]
I wanna also package qemu for my project [DistroHopper](https://github.com/oSoWoSo/DistroHopper) which use qemu together with [quickemu](https://github.com/quickemu-project/quickemu) for downloading and running a lot of OSes...

I'll be watching..

Hopefully we can get it to work...

**Comment by zen0bit** [comment]
@newyorkthink

Just look to first closed issue...
I will try that later...

Maybe @lucasmz1 you can put some instructions to readme...

**Comment by zen0bit** [comment]
working as stated in #1

**Comment by lucasmz1** [comment]
> ![image](https://user-images.githubusercontent.com/87791643/270515084-e08e3bd0-c936-42a7-b97a-0f2b8e93e32c.png)

hello friend! it actually works, but you must pass the right parameters to it.

here in this link you may find some useful commands to use with it.

https://github.com/lucasmz1/Qemu_Appimage/blob/main/qemu%20comando
