### ISSUE TITLE
cannot support

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#4]
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/cec95f9a-e153-4b1d-94d1-177153cd8b1c)
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/d7e524ef-fd14-438a-8790-82642da980b2)

**Comment by lucasmz1** [comment]
hello friend, if you're using the git/compiled one the avaible -vga options are none, std, cirrus, vmware, xenfb and virtio which means I didn't compiled qxl option yet, but due your request I'll may try it later.

and -chardev the avaible options are: Available, ringbuf, mux, pipe, stdio, pty, null, msmouse, socket, braille, vc, parallel, dbus, udp, file, wctablet, serial, memory and testdev.

but i guess the last one virtserialport is avaible "virtserialport", bus virtio-serial-bus

see the "./QEMU-git.AppImage qemu-system-x86_64 -device help" without qoutes. (by the way I renamed my qemu binary).

**Comment by lucasmz1** [comment]
by the way thanks for your bug report it helps me to see the users needs.
if you need something and cannot find me here to help you I'll be gald to receive you text message through my telegram, seek for zainotel.

**Comment by lucasmz1** [comment]
right now I am recopilling the software with spice enable. when it finishes download it and test it.

**Comment by lucasmz1** [comment]
it's done try it now.

**Comment by lucasmz1** [comment]
@newyorkthink so my friend did I fix your problem ?

**Comment by newyorkthink** [comment]
> @newyorkthink so my friend did I fix your problem ?

yes ,this is fixed
