### ISSUE TITLE
hi , cannot share Hosting Clipboard

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#5]

**Comment by newyorkthink** [comment]
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/db76e7a9-f2b5-4e11-a532-3d94c86a2211)

**Comment by newyorkthink** [comment]
https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/d0da1665-cd96-4786-94e3-2b9fa6144a43

**Comment by newyorkthink** [comment]
and , i try use share folder in kvm win10 , is not work
and, i not have telegram

**Comment by lucasmz1** [comment]
ok I'll see what I can do.

**Comment by lucasmz1** [comment]
> and , i try use share folder in kvm win10 , is not work and, i not have telegram

to share a folder inside o kvm or qemu, you must do this command:
 ./QEMU-git.AppImage qemu-system-x86_64 -M q35 -vga virtio -enable-kvm -vga qxl -display gtk,gl=on -cpu host -smp cores=2 -m 1G -name 'Xubuntu' -boot d -hda ~/Documentos/organizar/slax.qcow2 -cdrom ~/Documentos/organizar/slax-64bit-slackware-15.0.4.iso -virtfs local,path=/home/lucas/Público/,mount_tag=host0,security_model=mapped,id=host0

the inside of the vm you must type this command:

mount -t 9p -o trans=virtio,version=9p2000.L host0 /home/lucas/Modelos/

**Comment by lucasmz1** [comment]
> > and , i try use share folder in kvm win10 , is not work and, i not have telegram
> 
> to share a folder inside o kvm or qemu, you must do this command: ./QEMU-git.AppImage qemu-system-x86_64 -M q35 -vga virtio -enable-kvm -vga qxl -display gtk,gl=on -cpu host -smp cores=2 -m 1G -name 'Xubuntu' -boot d -hda ~/Documentos/organizar/slax.qcow2 -cdrom ~/Documentos/organizar/slax-64bit-slackware-15.0.4.iso -virtfs local,path=/home/lucas/Público/,mount_tag=host0,security_model=mapped,id=host0
> 
> the inside of the vm you must type this command:
> 
> mount -t 9p -o trans=virtio,version=9p2000.L host0 /home/lucas/Modelos/

I belive there must be a command for windows 10, unfortunately I am not a qemu specialist.

**Comment by lucasmz1** [comment]
well I tried the command above and also didn't work I may try to compile qemu with new flags for support this mount point, I saw in qemu config file that qemu clipboard-gtk is experimental I may not try it. If you have other issue please bug report me, and please try the builds I made using ubuntu like they can fulfil your needs

**Comment by lucasmz1** [comment]
have you tried that ? https://askubuntu.com/questions/858649/how-can-i-copypaste-from-the-host-to-a-kvm-guest

**Comment by lucasmz1** [comment]
sorry my friend I tried everything... but stills not working, I saw the flags I use to compile qemu and there spice protocol and spice agent is all enabled.

**Comment by lucasmz1** [comment]
well according to what I have read on the internet you must install sudo apt install spice-vdagent on the vm in order to run copy and paste from the clipboard, I didn't tested yet.

**Comment by newyorkthink** [comment]
I installed  spice-vdagent , but it not work

**Comment by newyorkthink** [comment]
> well I tried the command above and also didn't work I may try to compile qemu with new flags for support this mount point, I saw in qemu config file that qemu clipboard-gtk is experimental I may not try it. If you have other issue please bug report me, and please try the builds I made using ubuntu like they can fulfil your needs

![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/cd402001-08ea-4fda-a627-c3c0b8f85fa6)

**Comment by lucasmz1** [comment]
ok there says that gtk-clippboard is experimental, but I'll enable it and build again.

**Comment by lucasmz1** [comment]
> > well I tried the command above and also didn't work I may try to compile qemu with new flags for support this mount point, I saw in qemu config file that qemu clipboard-gtk is experimental I may not try it. If you have other issue please bug report me, and please try the builds I made using ubuntu like they can fulfil your needs
> 
> ![image](https://private-user-images.githubusercontent.com/87791643/299900795-cd402001-08ea-4fda-a627-c3c0b8f85fa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTYzOTQsIm5iZiI6MTcwNjI5NjA5NCwicGF0aCI6Ii84Nzc5MTY0My8yOTk5MDA3OTUtY2Q0MDIwMDEtMDhlYS00ZmRhLWE2MjctYzNjMGI4Zjg1ZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE5MDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NTMxOTA4YWNiY2QyNDQ3ZDFiMzQ4MTlmYzU3YzAyYzJhNDQyNjA3ZDVlZWQzYWQ2NmMyZjdiOTE2OWI4ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YLrdLKg4QWyOM5UrAV1N2hR-mkleke1Rbsd4DABNnFQ)

I have enable the flag --enable-gtk-clipboard in qemu during the build process, but I still not getting how to make it work. please if it doesn't work for you seek for a way to mount the qcow2 hdd on your system, that's might be a better solution until we don't find the way to copy and paste into the guest vm.

**Comment by lucasmz1** [comment]
@newyorkthink Did it work ?

**Comment by newyorkthink** [comment]
> @newyorkthink Did it work ?

i am sorry , is no work

**Comment by lucasmz1** [comment]
@newyorkthink Ok, I'll try to see what I can do. it's a little bit complicated to me cause I'm not a qemu expert.

**Comment by lucasmz1** [comment]
Did try to start the vdagent daemon?

**Comment by lucasmz1** [comment]
I'll download here the kali linux and see how to handle with it. But it may take a while.

**Comment by lucasmz1** [comment]
@newyorkthink hello friend, unfortunatally I couldn't find a solution for copy and paste, but I found another solution.

in the host os type this command:

./QEMU-git.AppImage qemu-system-x86_64 -M q35 -enable-kvm -vga virtio -display gtk,gl=on -cpu host -smp cores=2 -m 1G -name 'Kali' -drive file=/home/lucas/Downloads/kali-linux-2023.4-qemu-amd64.qcow2,format=qcow2 -device virtio-9p-pci,fsdev=shared,mount_tag=shared,id=shared -fsdev local,id=shared,security_model=none,path=/home/lucas/Downloads/

inside of the guest os type this command:

sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=262144 shared /home/kali/Downloads/

this will share a folder between the host and guest OS. for now this may be a solution until I fugure out a solution for copy and paste into qemu vm.

**Comment by newyorkthink** [comment]
> @newyorkthink hello friend, unfortunatally I couldn't find a solution for copy and paste, but I found another solution.
> 
> in the host os type this command:
> 
> ./QEMU-git.AppImage qemu-system-x86_64 -M q35 -enable-kvm -vga virtio -display gtk,gl=on -cpu host -smp cores=2 -m 1G -name 'Kali' -drive file=/home/lucas/Downloads/kali-linux-2023.4-qemu-amd64.qcow2,format=qcow2 -device virtio-9p-pci,fsdev=shared,mount_tag=shared,id=shared -fsdev local,id=shared,security_model=none,path=/home/lucas/Downloads/
> 
> inside of the guest os type this command:
> 
> sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=262144 shared /home/kali/Downloads/
> 
> this will share a folder between the host and guest OS. for now this may be a solution until I fugure out a solution for copy and paste into qemu vm.

hi , i have some discussion:
just copy text function.

we can use qemu-guest-agent, but this have problem,
i test, qemu-agent service cannot run in kvm with appimage file, i search it, maybe host need qemu some thing
so, can you make some thing to test copy text function

**Comment by lucasmz1** [comment]
@newyorkthink Well I wish I could help you, but I am not a qemu expert and I don't know what else should be packed in qemu in order to have guest-agent and also copy and paste function working. I believe I need to study more qemu.

by the way have you tried an old build of qemu ? I made some old builds that is not made from the source code it may help you. try it please and then give me a feedback.

**Comment by newyorkthink** [comment]
the bug is fixed, i cloed
