### ISSUE TITLE
use qemu appimage to run vm, but in guest os cannot enable qemu-agent

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#6]
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/d90db1a8-c871-45b8-adc5-eb4b9e73a7dc)

**Comment by lucasmz1** [comment]
@newyorkthink 

what os are you trying to use qemu-guest-agent?
does it have systemd?

**Comment by lucasmz1** [comment]
well I don't know what you are trying to do. I need more details.
this way I can try to find a solution for you.
I've opened my kali linux vm and runned this codes above you shown and it's working.
gimme more details and this way I can figure a way out.

**Comment by newyorkthink** [comment]
> well I don't know what you are trying to do. I need more details. this way I can try to find a solution for you. I've opened my kali linux vm and runned this codes above you shown and it's working. gimme more details and this way I can figure a way out.

hi, thanks, 
i have very busy now,
and, two month , i re-try it .
and i test ubuntu and kali kvm vm guest, it not wokr

**Comment by lucasmz1** [comment]
@newyorkthink ok my friend I'll be right here any time you need. Take care!

**Comment by newyorkthink** [comment]
> @newyorkthink ok my friend I'll be right here any time you need. Take care!

when i download qem
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/b5376347-a157-481d-9ea6-2070b2cc21f0)

download it and rename vm file

![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/7437f7be-1db6-464d-ae4b-7b2ab86409c1)

and use this argu to run it with you builded qemu appimage
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/880da74c-5bff-4a8a-89a2-394866b7be15)
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/7c4cf25b-3c82-468e-9bc9-158d886dea0a)


qemu cannot enable:
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/2ef36536-054e-4a97-8048-453ce2074e72)

and the qemu file default user
user:kali
password:kali

you can download it and test.
but i test

**Comment by lucasmz1** [comment]
@newyorkthink Sorry for my delay, I was afk for a few days!
Now I'll try to see what's possible to do.
thanks for your reply.

**Comment by lucasmz1** [comment]
@newyorkthink

Ok, I understand what you've said, but I need more details.

what do you wanna do with that? what's the result you expect e.g. make an snapshot of this virtual machine or mount a shared folder?

**Comment by lucasmz1** [comment]
well I'm not a qemu expert, I've tried everything and couldn't find a solution.
thry this.
https://wiki.qemu.org/Features/GuestAgent

**Comment by newyorkthink** [comment]
the bug is fixed too
