### ISSUE TITLE
Virgil rendering

### ISSUE THREAD

**Issue by msmalik681** [lucasmz1/Qemu_Appimage#7]
Great project I also tried to make a appimage but it would not work for me if you could make a tutorial on how to made it I would be very interested to read.

The issue is I am trying to run with options "-device virtio-vga,virgl=on -display sdl,gl=on" but I get the error "qemu-system-x86_64: -device virtio-vga,virgl=on: Property 'virtio-vga.virgl' not found".

**Comment by lucasmz1** [comment]
about the tutorial I've made videos but it's all in Portuguese in my telegram group, wish I could help you about that.

I've made a quick search on the web about virgl and my project yet don't support it, I'll see in the source code if there's a way to enable it... I saw in the compiled binary and there no qemu-virgl being compiled.
have a look in this tutorial over here
https://www.dedoimedo.com/computers/qemu-virgil.html
I'll have a look if I can do something for you, stay around!

**Comment by msmalik681** [comment]
here is a video that explains how to compile qemu with virgil support: https://youtu.be/bz8FugjsHs8?si=lY_q8k5O1NKOQGL8

I managed to build qemu just could not convert that built application into a appimage.

**Comment by lucasmz1** [comment]
Hi! I'm having internet connections issues today, hope you can wait until I have a stable connection over here.

**Comment by msmalik681** [comment]
Yeah sure I really hope you can add virgil support then this vm could be used for light gaming.

**Comment by lucasmz1** [comment]
as you can see here https://github.com/lucasmz1/Qemu_Appimage/blob/main/.github/workflows/blank.yml I've enabled virgl, but if it compiles extras binaries I may need to make changes into the AppRun file for running them, then it's gonna take another build process.

**Comment by lucasmz1** [comment]
if you need personal support seek for me on telegram zainotel

**Comment by lucasmz1** [comment]
> Great project I also tried to make a appimage but it would not work for me if you could make a tutorial on how to made it I would be very interested to read.
> 
> The issue is I am trying to run with options "-device virtio-vga,virgl=on -display sdl,gl=on" but I get the error "qemu-system-x86_64: -device virtio-vga,virgl=on: Property 'virtio-vga.virgl' not found".

if still giving this error read this https://www.reddit.com/r/archlinux/comments/prmzeb/qemu_with_virgl_doesnt_work_anymore/

**Comment by msmalik681** [comment]
This option also does not work.
qemu-system-x86_64: -device virtio-vga-gl: 'virtio-vga-gl' is not a valid device model name

**Comment by msmalik681** [comment]
I did not download the latest release lol its working perfect thanks your a legend.
