### ISSUE TITLE
i have some good news for you, and some problem . you are great :)

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#8]
First news:
the qemu-guest-agent.service can be enabled
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/1ddfeee8-be23-441c-90c3-272a8db20e52)

second news:
the kvm machine clipboard is working:
![Peek 2024-04-18 11-57](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/f588610d-fb0d-4669-9d5d-4a33eece6847)

the kvm config must like this for you:
```
            'qemu \
            qemu-system-x86_64 \
            -enable-kvm \
            -M q35 \
            -name ' + vm_name +
            ' -smp cores=2 \
            -m 6G \
            -hda ' + vm_path + vm_file +
            ' -boot order=cd \
            -vga qxl \
            -cpu host \
            -overcommit cpu-pm=on \
            -device ich9-intel-hda,addr=1f.1 -audiodev pa,id=snd0 -device hda-output,audiodev=snd0 \
            -usb -usbdevice tablet \
            -device virtio-serial-pci \
            -chardev qemu-vdagent,id=ch1,name=vdagent,clipboard=on \
            -device virtserialport,chardev=ch1,id=ch1,name=com.redhat.spice.0 \
            -chardev socket,path=/tmp/qga.sock,server=on,wait=off,id=qga0 \
            -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 \
            -fsdev local,id=fsdev0,path=/home/thinker/,security_model=none \
            -device virtio-9p-pci,fsdev=fsdev0,mount_tag=sharedfolder \
            -display gtk,show-menubar=off,full-screen=off \
            >/dev/null 2>&1 &
```

###################################################

but , have some problems :+1: 
the chardev qemu-vdagent,id=ch1,name=vdagent,clipboard=on \ => clipboard=on cannot paste picture in the kvm guest os
it just paste fonts

and the "lubuntu os" guest os cannot auto size screen , it always display 1048x 768 on start. my temporary function is using:
"xrandr --output Virtual-1 --mode 1920x1080 --pos 0x0 --rotate normal" this command. do you have some ideas :)

and the win10 guest os cannot share folder always

**Comment by newyorkthink** [comment]
i forget, you qemu appimage doesn't have show icon:
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/e9b7951f-2862-41b1-9a40-e6962a781203)

i use alttab :https://github.com/sagb/alttab

**Comment by newyorkthink** [comment]
![image](https://github.com/lucasmz1/Qemu_Appimage/assets/87791643/66bfc226-0867-4e5e-8216-e4c3ca3fd510)

```
(qemu:985323): Gtk-WARNING **: 13:15:13.992: drawing failure for widget 'GtkDrawingArea': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:13.992: drawing failure for widget 'GtkNotebook': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:13.992: drawing failure for widget 'GtkBox': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:13.992: drawing failure for widget 'GtkWindow': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.019: drawing failure for widget 'GtkDrawingArea': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.019: drawing failure for widget 'GtkNotebook': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.019: drawing failure for widget 'GtkBox': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.019: drawing failure for widget 'GtkWindow': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.045: drawing failure for widget 'GtkDrawingArea': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.045: drawing failure for widget 'GtkNotebook': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.045: drawing failure for widget 'GtkBox': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.045: drawing failure for widget 'GtkWindow': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.046: drawing failure for widget 'GtkDrawingArea': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.046: drawing failure for widget 'GtkNotebook': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.046: drawing failure for widget 'GtkBox': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.046: drawing failure for widget 'GtkWindow': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.055: drawing failure for widget 'GtkDrawingArea': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.055: drawing failure for widget 'GtkNotebook': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.055: drawing failure for widget 'GtkBox': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.055: drawing failure for widget 'GtkWindow': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkDrawingArea': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkNotebook': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkBox': invalid value for stride

(qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkWindow': invalid value for stride
```

```
(qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkWindow': invalid value for stride
qemu: warning: atk-bridge: get_device_events_reply: unknown signature
```

and have some bug

**Comment by newyorkthink** [comment]
Can not drag-drop or copy-paste files between guest and host

**Comment by lucasmz1** [comment]
> First news: the qemu-guest-agent.service can be enabled ![image](https://private-user-images.githubusercontent.com/87791643/323459709-1ddfeee8-be23-441c-90c3-272a8db20e52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjQ3NzcsIm5iZiI6MTcxMzQ2NDQ3NywicGF0aCI6Ii84Nzc5MTY0My8zMjM0NTk3MDktMWRkZmVlZTgtYmUyMy00NDFjLTkwYzMtMjcyYThkYjIwZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE4MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZmZmNzc2NjQ5YTRjMmQ3YmM2ZDA0NTU0NDQ0OWU3M2M0Mzg5YzA2ZDYyMzA3NTNkNzJiYmY4YjEyNWYwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5lgxNahS_ccBxbqwIhvF6EpE7jb6wuG_TD7WFd00bsk)
> 
> second news: the kvm machine clipboard is working: ![Peek 2024-04-18 11-57](https://private-user-images.githubusercontent.com/87791643/323460634-f588610d-fb0d-4669-9d5d-4a33eece6847.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjQ3NzcsIm5iZiI6MTcxMzQ2NDQ3NywicGF0aCI6Ii84Nzc5MTY0My8zMjM0NjA2MzQtZjU4ODYxMGQtZmIwZC00NjY5LTlkNWQtNGEzM2VlY2U2ODQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE4MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NWU0YWY3NzhhNTI1MGU5MDM5YzhjY2RhNjI5YjI2OGUyNjhkMDIyNTlhYWRiZWIyZDNiMGNiNjE5OGY5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o9-qZHdTYQ9FXDzwmEb5pSKY_q7dQp0CZT2Tt7PxWqE) [ ![Peek 2024-04-18 11-57](https://private-user-images.githubusercontent.com/87791643/323460634-f588610d-fb0d-4669-9d5d-4a33eece6847.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjQ3NzcsIm5iZiI6MTcxMzQ2NDQ3NywicGF0aCI6Ii84Nzc5MTY0My8zMjM0NjA2MzQtZjU4ODYxMGQtZmIwZC00NjY5LTlkNWQtNGEzM2VlY2U2ODQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE4MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NWU0YWY3NzhhNTI1MGU5MDM5YzhjY2RhNjI5YjI2OGUyNjhkMDIyNTlhYWRiZWIyZDNiMGNiNjE5OGY5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o9-qZHdTYQ9FXDzwmEb5pSKY_q7dQp0CZT2Tt7PxWqE) ](https://private-user-images.githubusercontent.com/87791643/323460634-f588610d-fb0d-4669-9d5d-4a33eece6847.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjQ3NzcsIm5iZiI6MTcxMzQ2NDQ3NywicGF0aCI6Ii84Nzc5MTY0My8zMjM0NjA2MzQtZjU4ODYxMGQtZmIwZC00NjY5LTlkNWQtNGEzM2VlY2U2ODQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE4MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NWU0YWY3NzhhNTI1MGU5MDM5YzhjY2RhNjI5YjI2OGUyNjhkMDIyNTlhYWRiZWIyZDNiMGNiNjE5OGY5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o9-qZHdTYQ9FXDzwmEb5pSKY_q7dQp0CZT2Tt7PxWqE) [ ](https://private-user-images.githubusercontent.com/87791643/323460634-f588610d-fb0d-4669-9d5d-4a33eece6847.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjQ3NzcsIm5iZiI6MTcxMzQ2NDQ3NywicGF0aCI6Ii84Nzc5MTY0My8zMjM0NjA2MzQtZjU4ODYxMGQtZmIwZC00NjY5LTlkNWQtNGEzM2VlY2U2ODQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE4MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NWU0YWY3NzhhNTI1MGU5MDM5YzhjY2RhNjI5YjI2OGUyNjhkMDIyNTlhYWRiZWIyZDNiMGNiNjE5OGY5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o9-qZHdTYQ9FXDzwmEb5pSKY_q7dQp0CZT2Tt7PxWqE)
> 
> the kvm config must like this for you:
> 
> ```
>             'qemu \
>             qemu-system-x86_64 \
>             -enable-kvm \
>             -M q35 \
>             -name ' + vm_name +
>             ' -smp cores=2 \
>             -m 6G \
>             -hda ' + vm_path + vm_file +
>             ' -boot order=cd \
>             -vga qxl \
>             -cpu host \
>             -overcommit cpu-pm=on \
>             -device ich9-intel-hda,addr=1f.1 -audiodev pa,id=snd0 -device hda-output,audiodev=snd0 \
>             -usb -usbdevice tablet \
>             -device virtio-serial-pci \
>             -chardev qemu-vdagent,id=ch1,name=vdagent,clipboard=on \
>             -device virtserialport,chardev=ch1,id=ch1,name=com.redhat.spice.0 \
>             -chardev socket,path=/tmp/qga.sock,server=on,wait=off,id=qga0 \
>             -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 \
>             -fsdev local,id=fsdev0,path=/home/thinker/,security_model=none \
>             -device virtio-9p-pci,fsdev=fsdev0,mount_tag=sharedfolder \
>             -display gtk,show-menubar=off,full-screen=off \
>             >/dev/null 2>&1 &
> ```
> 
> ###################################################
> 
> but , have some problems 👍 the chardev qemu-vdagent,id=ch1,name=vdagent,clipboard=on \ => clipboard=on cannot paste picture in the kvm guest os it just paste fonts
> 
> and the "lubuntu os" guest os cannot auto size screen , it always display 1048x 768 on start. my temporary function is using: "xrandr --output Virtual-1 --mode 1920x1080 --pos 0x0 --rotate normal" this command. do you have some ideas :)
> 
> and the win10 guest os cannot share folder always

this is what chatgpt recommends!

https://chat.openai.com/share/cd627ba3-0686-4466-8a31-fefbf1962242

**Comment by lucasmz1** [comment]
> ![image](https://private-user-images.githubusercontent.com/87791643/323474473-66bfc226-0867-4e5e-8216-e4c3ca3fd510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjQ3NzcsIm5iZiI6MTcxMzQ2NDQ3NywicGF0aCI6Ii84Nzc5MTY0My8zMjM0NzQ0NzMtNjZiZmMyMjYtMDg2Ny00ZTVlLTgyMTYtZTRjM2NhM2ZkNTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE4MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNjM5NGNjYmJlOGFkMTNmZjEwZTM1MzU1NjhkZGM3M2JkNzRlYjVhZTRjMTE5NmEwZmVkMGRmY2Y0MjA0YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R7086Gg4rLLnrovr0iM6nEqmr_8bIpEOIJAGDlf0wkI)
> 
> ```
> (qemu:985323): Gtk-WARNING **: 13:15:13.992: drawing failure for widget 'GtkDrawingArea': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:13.992: drawing failure for widget 'GtkNotebook': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:13.992: drawing failure for widget 'GtkBox': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:13.992: drawing failure for widget 'GtkWindow': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.019: drawing failure for widget 'GtkDrawingArea': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.019: drawing failure for widget 'GtkNotebook': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.019: drawing failure for widget 'GtkBox': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.019: drawing failure for widget 'GtkWindow': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.045: drawing failure for widget 'GtkDrawingArea': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.045: drawing failure for widget 'GtkNotebook': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.045: drawing failure for widget 'GtkBox': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.045: drawing failure for widget 'GtkWindow': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.046: drawing failure for widget 'GtkDrawingArea': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.046: drawing failure for widget 'GtkNotebook': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.046: drawing failure for widget 'GtkBox': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.046: drawing failure for widget 'GtkWindow': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.055: drawing failure for widget 'GtkDrawingArea': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.055: drawing failure for widget 'GtkNotebook': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.055: drawing failure for widget 'GtkBox': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.055: drawing failure for widget 'GtkWindow': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkDrawingArea': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkNotebook': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkBox': invalid value for stride
> 
> (qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkWindow': invalid value for stride
> ```
> 
> ```
> (qemu:985323): Gtk-WARNING **: 13:15:14.072: drawing failure for widget 'GtkWindow': invalid value for stride
> qemu: warning: atk-bridge: get_device_events_reply: unknown signature
> ```
> 
> and have some bug

this is a bug from your host os, maybe is lacking something related to gtk on your os.
just ignore this warnings. I take a lot of warnings related to gtk when packing my appimages.
but I can do something about it, redirect everything to /dev/null this will hide all over your warnings but warnings are necessary to understand what's going on!

**Comment by newyorkthink** [comment]
I try doing some thing, but not working
