### ISSUE TITLE
quickemu AppImage

### ISSUE THREAD

**Issue by zen0bit** [lucasmz1/Qemu_Appimage#9]
Since you already helped me :+1: with this

I am creating issue here since this is most appropriate place which I yet met.

Hope you don't mind.

I am trying to build AppImage with quickemu. (qemu + quickemu + my TUI for easy of use)

Any help with this welcomed
https://github.com/oSoWoSo/DistroHopper/tree/appimage-q
Will update with my progress (In quickemu repo nobody seems to help me)
https://github.com/quickemu-project/quickemu/issues/772
Can I create PR here what I got so far?

quickemu requirements:
[QEMU](https://www.qemu.org/) (6.0.0 or newer) with GTK, SDL, SPICE & VirtFS support
    [bash](https://www.gnu.org/software/bash/) (4.0 or newer)
    [Coreutils](https://www.gnu.org/software/coreutils/)
    [curl](https://curl.se/)
    [EDK II](https://github.com/tianocore/edk2)
    [grep](https://www.gnu.org/software/grep/)
    [jq](https://stedolan.github.io/jq/)
    [LSB](https://wiki.linuxfoundation.org/lsb/start)
    [procps](https://gitlab.com/procps-ng/procps)
    [python3](https://www.python.org/)
    [chunkcheck](https://gist.github.com/MCJack123/943eaca762730ca4b7ae460b731b68e7)
    [mkisofs](http://cdrtools.sourceforge.net/private/cdrecord.html)
    [usbutils](https://github.com/gregkh/usbutils)
    [util-linux](https://github.com/karelzak/util-linux)
    [sed](https://www.gnu.org/software/sed/)
    [socat](http://www.dest-unreach.org/socat/)
    [spicy](https://gitlab.freedesktop.org/spice/spice-gtk)
    [swtpm](https://github.com/stefanberger/swtpm)
    [Wget](https://www.gnu.org/software/wget/)
    [xdg-user-dirs](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/)
    [xrandr](https://gitlab.freedesktop.org/xorg/app/xrandr)
    [zsync](http://zsync.moria.org.uk/)
    [unzip](http://www.info-zip.org/UnZip.html)

**Comment by lucasmz1** [comment]
No problem brother you can open issue as many as you like.
well I never had any plan to build quickemu but I can try to help you.
what was the step you've get stucked during the compilation time?

**Comment by zen0bit** [comment]
Compilation was done.
Not done build recently, just updated from your repo and will try what happen.

Last time I builded sucessfuly but qemu inside don't have everything needed. Will try do that in action.

**Comment by lucasmz1** [comment]
Please provide the steps you are taking to make this AppImage or the build you are trying to do?

**Comment by lucasmz1** [comment]
find me in telegram for we discuss about it @zainotel
